### ISSUE TITLE
Technique of fine-tuning

### ISSUE THREAD

**Issue by fshamsafar** [suhangpro/cnn-finetune#2]
Dear Hang,

I found your code very useful. I just wonder why you have used the following technique to fine-tune:

% tune last layer --> tune fc layers --> tune all layers

Why don't you just change the last fc layer weights and continue training the whole network with the new weights defined in the last fc layer? Why don't you just use the following command only once and instead, you have put this command in a for-loop defined by "s"?

[net, info] = cnn_train(net, imdb,.....

**Comment by suhangpro** [comment]
multi-stage fine-tuning is just a trick many found useful and takes shorter time to reach a lower error rate.
